name: Test DMT Lint (Manual)

on:
  push:
    branches:
      - test/lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: DMT Lint
        uses: deckhouse/modules-actions/lint@fix/trdl-action-link